deploy: "dev"

server:
  port: 8084
  domain: 127.0.0.1

db:
  postgres:
    host: 127.0.0.1
    port: 5432
    username: admin
    password: postgres
    dbname: daily_note
    minPoolSize: 10
    maxPoolSize: 30

jwt:
  expiredDays: 3
  secret: "magiclianhostonly666"